name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '23.x'
          cache: 'npm'

      - name: Check Version
        run: ./scripts/check_version.sh

      - name: Build
        run: npm ci

      - name: Test
        run: npm test
